Bump minimal OCaml version from 4.02 to 4.03
Following the previous base64 upgrade which now uses 4.03+ "result"
type.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -132,8 +132,8 @@ fi
 echo "ocaml version: $OCAML_VERSION"
 
 case $OCAML_VERSION in
-    3.*|4.00.*|4.01.*)
-        echo "configure: error: OCaml version ($OCAML_VERSION) is too old -- need >= 4.02; See INSTALL for details" 1>&2
+    3.*|4.00.*|4.01.*|4.02.*)
+        echo "configure: error: OCaml version ($OCAML_VERSION) is too old -- need >= 4.03; See INSTALL for details" 1>&2
         exit 1
         ;;
 esac
